// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://cyqvssbyewwpnkmqgvaz.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5cXZzc2J5ZXd3cG5rbXFndmF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA0MzkxMTMsImV4cCI6MjA0NjAxNTExM30.nKstp_UYxjCCmylvIRBVGrjna1bchEKx9yMpcM9wfbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);